spring:
  application:
    name: my-spring-study-diary

  # 데이터베이스 설정
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:diary_db}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME:myuser}
    password: ${DB_PASSWORD:mypassword}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000

#  sql:
#    init:
#      mode: always
#      schema-locations: classpath:db/schema.sql
#      data-locations: classpath:db/data.sql

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        default_batch_fetch_size: 100
    open-in-view: false

# 로깅 설정
logging:
  level:
    root: INFO
    com.study.myspringstudydiary: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# 서버 설정
#server:
#  port: ${APP_PORT:8080}
#  servlet:
#    context-path: /
#    encoding:
#      charset: UTF-8
#      enabled: true
#      force: true

